// ══════════════════════════════════════════════════════════
//  MODULE : Compétences Digitales
//  20 questions · 20 minutes
// ══════════════════════════════════════════════════════════
const MODULE_DIGITAL = {
  id:       "digital",
  label:    "Compétences Digitales",
  icon:     "💻",
  duration: "20 minutes",
  seconds:  20 * 60,
  hasPdf:   false,
  pdfPath:  null,
  questions: [
    {type:"single",q:"Dans un tableur, la cellule A1 contient 200 et la cellule A2 contient 50. Quelle formule affiche le pourcentage que représente A2 par rapport à A1 ?",choices:[{l:"A",t:"=A1/A2*100"},{l:"B",t:"=A2-A1"},{l:"C",t:"=A2/A1*100"},{l:"D",t:"=A1*A2/100"}],answer:"c"},
    {type:"single",q:"Quelle est la différence entre « Enregistrer » et « Enregistrer sous » dans un traitement de texte ?",choices:[{l:"A",t:"« Enregistrer » crée une copie du fichier, « Enregistrer sous » met à jour l'original."},{l:"B",t:"« Enregistrer » met à jour le fichier existant, « Enregistrer sous » crée un nouveau fichier ou change l'emplacement."},{l:"C",t:"Les deux fonctions font exactement la même chose."},{l:"D",t:"« Enregistrer sous » supprime l'ancienne version du fichier automatiquement."}],answer:"b"},
    {type:"single",q:"Quel format de fichier est le plus adapté pour partager un document dont on veut préserver la mise en forme et empêcher les modifications faciles ?",choices:[{l:"A",t:".docx"},{l:"B",t:".txt"},{l:"C",t:".xlsx"},{l:"D",t:".pdf"}],answer:"d"},
    {type:"single",q:"Dans un moteur de recherche, quel opérateur permet de chercher une expression exacte ?",choices:[{l:"A",t:"Des parenthèses : (intelligence artificielle)"},{l:"B",t:'Des guillemets : "intelligence artificielle"'},{l:"C",t:"Un astérisque : *intelligence artificielle*"},{l:"D",t:"Un signe plus : +intelligence artificielle"}],answer:"b"},
    {type:"single",q:"Dans un tableur, les cellules C2 à C6 contiennent les valeurs 8, 12, 5, 15, 10. Que retourne la formule =MAX(C2:C6) ?",choices:[{l:"A",t:"10"},{l:"B",t:"50"},{l:"C",t:"15"},{l:"D",t:"12"}],answer:"c"},
    {type:"single",q:"Les notes B2:B8 sont : 17, 15, 14, 12, 11, 7, 4,5. La cellule B10 affiche 11,5. Quelle est la formule de la cellule B10 ?",choices:[{l:"A",t:"=MAX(B2:B8)"},{l:"B",t:"=SOMME(A2:A8)"},{l:"C",t:"=MOYENNE(A2:A8)"},{l:"D",t:"=MOYENNE(B2:B8)"}],answer:"d"},
    {type:"single",q:"Qu'est-ce qu'une « bulle de filtres » sur les réseaux sociaux ?",choices:[{l:"A",t:"Un type de filtre utilisé pour améliorer la qualité des photos."},{l:"B",t:"Un espace virtuel où les utilisateurs peuvent discuter en privé."},{l:"C",t:"Un algorithme qui montre uniquement du contenu similaire à celui déjà consulté par l'utilisateur."},{l:"D",t:"Un groupe de hashtags populaires."}],answer:"c"},
    {type:"single",q:"Quel réseau social est principalement utilisé pour établir des connexions professionnelles et rechercher des opportunités d'emploi ?",choices:[{l:"A",t:"Facebook"},{l:"B",t:"Twitter"},{l:"C",t:"LinkedIn"},{l:"D",t:"Instagram"}],answer:"c"},
    {type:"single",q:"Quel terme désigne le fait de créer de faux comptes ou de fausses identités sur les réseaux sociaux pour tromper les autres utilisateurs ?",choices:[{l:"A",t:"Phishing"},{l:"B",t:"Spoofing"},{l:"C",t:"Harcèlement en ligne"},{l:"D",t:"Impersonation"}],answer:"d"},
    {type:"single",q:"Quel terme désigne la pratique consistant à acheter de faux abonnés, likes ou commentaires sur les réseaux sociaux pour paraître plus populaire ?",choices:[{l:"A",t:"Follower farming"},{l:"B",t:"Social spamming"},{l:"C",t:"Astroturfing"},{l:"D",t:"Hashtagging"}],answer:"a"},
    {type:"single",q:"Qu'est-ce que le « droit à l'oubli » sur Internet ?",choices:[{l:"A",t:"Le droit de supprimer son compte sur n'importe quel réseau social sans justification."},{l:"B",t:"Le droit de ne pas être photographié dans un lieu public."},{l:"C",t:"Le droit de demander la suppression de ses données personnelles auprès d'un service en ligne."},{l:"D",t:"Le droit d'accéder anonymement à tous les services en ligne sans créer de compte."}],answer:"c"},
    {type:"single",q:"Qu'est-ce qu'un mot de passe fort ?",choices:[{l:"A",t:"Un mot de passe composé uniquement de lettres minuscules facile à retenir."},{l:"B",t:"Un mot de passe combinant majuscules, minuscules, chiffres et caractères spéciaux d'au moins 12 caractères."},{l:"C",t:"Un mot de passe identique sur tous vos comptes pour ne pas l'oublier."},{l:"D",t:"Un mot de passe composé de votre prénom suivi de votre année de naissance."}],answer:"b"},
    {type:"single",q:"Qu'est-ce que le phishing (hameçonnage) ?",choices:[{l:"A",t:"Une technique de compression de fichiers pour les envoyer par email."},{l:"B",t:"Un logiciel permettant de filtrer les spams dans une boîte mail."},{l:"C",t:"Un virus qui chiffre les fichiers de l'ordinateur et demande une rançon."},{l:"D",t:"Une tentative frauduleuse d'obtenir des informations personnelles en se faisant passer pour une entité de confiance."}],answer:"d"},
    {type:"single",q:"Parmi ces propositions, laquelle décrit le mieux le rôle d'un système d'exploitation ?",choices:[{l:"A",t:"Gérer les ressources matérielles et logicielles de l'ordinateur et faire l'interface entre l'utilisateur et la machine."},{l:"B",t:"Permettre uniquement la connexion à Internet et la navigation sur le web."},{l:"C",t:"Créer et modifier des documents texte, des tableurs et des présentations."},{l:"D",t:"Protéger l'ordinateur contre les virus et les logiciels malveillants."}],answer:"a"},
    {type:"single",q:"Soit x=0, boucle « tant que x < 5, x = x + 2 ». Quelle est la valeur finale de x ?",choices:[{l:"A",t:"5"},{l:"B",t:"6"},{l:"C",t:"4"},{l:"D",t:"8"}],answer:"b"},
    {type:"single",q:"Soit x=0, boucle « tant que x < 100, x = x + 5 ». Combien d'itérations pour que l'algorithme s'arrête ?",choices:[{l:"A",t:"20"},{l:"B",t:"19"},{l:"C",t:"21"},{l:"D",t:"25"}],answer:"a"},
    {type:"single",q:"Boucle « pour i allant de 1 à n, x = x + i » avec x=0. Quelle est la valeur finale de x si n = 4 ?",choices:[{l:"A",t:"i"},{l:"B",t:"4"},{l:"C",t:"15"},{l:"D",t:"10"}],answer:"d"},
    {type:"single",q:"Qu'est-ce qu'une bibliographie dans un document textuel ?",choices:[{l:"A",t:"Une liste des éditeurs potentiels du document."},{l:"B",t:"Une liste des sources et des références citées dans le document."},{l:"C",t:"Une section du document réservée aux graphiques et aux images."},{l:"D",t:"Une section du document contenant des exemples pratiques."}],answer:"b"},
    {type:"single",q:"Qu'est-ce que l'accessibilité dans le contexte de la création de documents textuels ?",choices:[{l:"A",t:"La facilité d'accès au document sur Internet."},{l:"B",t:"La simplicité du langage utilisé dans le document."},{l:"C",t:"La convivialité du design du document."},{l:"D",t:"L'adaptation du document pour qu'il soit utilisable par un large public, y compris les personnes handicapées."}],answer:"d"},
    {type:"single",q:"Qu'est-ce qu'une infographie ?",choices:[{l:"A",t:"Un type de diagramme à secteurs."},{l:"B",t:"Une représentation visuelle des données."},{l:"C",t:"Un texte explicatif d'un tableau de données."},{l:"D",t:"Un document qui agrège les données entre elles."}],answer:"b"},
  ]
};
