// ══════════════════════════════════════════════════════════
//  MODULE : Analyse Documentaire (OGM)
//  20 questions · 2 heures · Dossier PDF requis
// ══════════════════════════════════════════════════════════
const MODULE_DOCS = {
  id:       "docs",
  label:    "Analyse Documentaire",
  icon:     "📄",
  duration: "2 heures",
  seconds:  120 * 60,
  hasPdf:   true,
  pdfPath:  "dossier_documentaire.pdf",
  questions: [
    // ── REPÉRAGE (Q1–Q6) ──
    {type:"single",section:"reperage",q:"Quelle était, en millions d'hectares, la surface totale de cultures génétiquement modifiées aux États-Unis en 2012 ?",choices:[{l:"A",t:"Environ 8,5"},{l:"B",t:"Environ 7"},{l:"C",t:"Environ 175"},{l:"D",t:"Environ 70"}],answer:"d"},
    {type:"single",section:"reperage",q:"Quelle proportion de la population de l'Union Européenne était, en 2010, contre la présence d'OGM dans l'alimentation ?",choices:[{l:"A",t:"70,9%"},{l:"B",t:"28%"},{l:"C",t:"33%"},{l:"D",t:"61%"}],answer:"d"},
    {type:"single",section:"reperage",q:"Qu'est-ce que le « Terminator » ?",choices:[{l:"A",t:"Un puissant insecticide."},{l:"B",t:"Une semence stérile."},{l:"C",t:"Un puissant herbicide."},{l:"D",t:"Une puissante multinationale américaine."}],answer:"b"},
    {type:"single",section:"reperage",q:"Que désigne l'Agrobacterium tumefaciens ?",choices:[{l:"A",t:"Une bactérie."},{l:"B",t:"Un gène."},{l:"C",t:"Un organisme génétiquement modifié."},{l:"D",t:"Un chromosome."}],answer:"a"},
    {type:"single",section:"reperage",q:"Quelle institution remplace l'accord général sur les tarifs douaniers et le commerce en 1995 ?",choices:[{l:"A",t:"La Convention sur la diversité biologique."},{l:"B",t:"Le Codex alimentarius."},{l:"C",t:"Le protocole de biosécurité."},{l:"D",t:"L'Organisation Mondiale du Commerce."}],answer:"d"},
    {type:"single",section:"reperage",q:"Combien de cas d'effets indésirables potentiellement liés à la consommation de maïs transgénique StarLink ont été recensés par les autorités américaines ?",choices:[{l:"A",t:"40"},{l:"B",t:"28"},{l:"C",t:"200"},{l:"D",t:"3"}],answer:"a"},
    // ── ANALYSE (Q7–Q12) ──
    {type:"multi",section:"analyse",hint:"Plusieurs réponses attendues — cochez toutes les bonnes réponses (tout ou rien).",q:"Quel message les deux images de l'ILLUSTRATION 4 véhiculent-elles ?",choices:[{l:"A",t:"Les OGM sont une solution au problème de la faim dans le monde."},{l:"B",t:"Les OGM permettent d'améliorer les techniques et les rendements agricoles."},{l:"C",t:"Les OGM sont responsables de nombreuses maladies à travers le monde et dégradent la planète."},{l:"D",t:"Les citoyens sont contraints de consommer des aliments contenant des OGM."},{l:"E",t:"Les citoyens sont favorables à la présence d'OGM dans leur alimentation."}],answers:["a","d"]},
    {type:"multi",section:"analyse",hint:"Plusieurs réponses attendues — cochez toutes les bonnes réponses (tout ou rien).",q:"Pour quelles raisons les consommateurs sont-ils méfiants voire hostiles à l'égard des OGM ?",choices:[{l:"A",t:"Il n'existe aucune institution chargée de contrôler les OGM."},{l:"B",t:"Les grandes firmes multinationales de biotechnologie sont accusées de lobbying."},{l:"C",t:"La traçabilité des OGM est insuffisante."},{l:"D",t:"La surface cultivée d'OGM croît de manière exponentielle au fil des années."},{l:"E",t:"Les OGM présentent des risques sanitaires et environnementaux majeurs."}],answers:["b","c","e"]},
    {type:"multi",section:"analyse",hint:"Plusieurs réponses attendues — cochez toutes les bonnes réponses (tout ou rien).",q:"Quels principes du protocole de Carthagène entrent en contradiction avec le cadre réglementaire fixé par l'OMC ?",choices:[{l:"A",t:"Il interdit le commerce d'OVM au nom du principe de précaution."},{l:"B",t:"Il permet aux pays membres de donner leur accord avant l'entrée d'OVM sur leur territoire."},{l:"C",t:"Il vise à assurer le partage équitable des bénéfices tirés de l'exploitation des ressources génétiques."},{l:"D",t:"Il interdit l'exportation de certains OVM jugés « à risque »."},{l:"E",t:"Il impose l'étiquetage des produits pouvant contenir des OVM."}],answers:["a","b"]},
    {type:"multi",section:"analyse",hint:"Plusieurs réponses attendues — cochez toutes les bonnes réponses (tout ou rien).",q:"Quels sont les reproches formulés à l'égard des grandes firmes multinationales semencières ?",choices:[{l:"A",t:"Leurs dépenses en Recherche et Développement sont insuffisantes."},{l:"B",t:"Elles détiennent une part trop importante du marché des semences."},{l:"C",t:"Les brevets qu'elles détiennent nuisent à la circulation de la connaissance."},{l:"D",t:"Elles sont créatrices de dépendances préjudiciables dans le domaine agricole."},{l:"E",t:"Elles sont tellement nombreuses qu'elles écrasent les agriculteurs indépendants."}],answers:["b","c","d"]},
    {type:"multi",section:"analyse",hint:"Plusieurs réponses attendues — cochez toutes les bonnes réponses (tout ou rien).",q:"Quels arguments permettent de justifier l'existence de brevets sur le vivant ?",choices:[{l:"A",t:"Ils permettent à travers la quête d'intérêts personnels d'aboutir à l'intérêt général."},{l:"B",t:"Ils enlèvent à la concurrence tout espoir d'exploiter et commercialiser l'invention protégée."},{l:"C",t:"Ils favorisent la circulation de la connaissance et améliorent la compétitivité d'une économie."},{l:"D",t:"Ils garantissent une exclusivité perpétuelle d'exploitation à l'inventeur, ce qui l'incite à innover."},{l:"E",t:"Ils favorisent l'innovation en augmentant les perspectives de profits des investisseurs."}],answers:["a","c","e"]},
    {type:"multi",section:"analyse",hint:"Plusieurs réponses attendues — cochez toutes les bonnes réponses (tout ou rien).",q:"Pourquoi faut-il nuancer les craintes suscitées par les OGM ?",choices:[{l:"A",t:"La présence d'OGM dans l'alimentation humaine est presque inexistante en France."},{l:"B",t:"Certains risques environnementaux imputés aux OGM ne sont pas établis et relèvent uniquement de l'hypothèse."},{l:"C",t:"Le poids de la surface cultivée avec des plants génétiquement modifiés est négligeable au niveau mondial."},{l:"D",t:"Les OGM favorisent la diversité des espèces animales et végétales."},{l:"E",t:"Les OGM pourraient permettre de développer une agriculture durable."},{l:"F",t:"(aucune autre option)"}],answers:["b","e"]},
    // ── SYNTHÈSE (Q13–Q20) ──
    {type:"fill",section:"synthese",q:"Introduction — Complétez l'accroche : « L'affaire du [x], grandement médiatisée, a mis en exergue les [y] liés à l'usage des OGM dans l'alimentation. »",hint:"Sélectionnez la valeur correcte pour chaque variable.",vars:[{key:"x",label:"Sujet de l'affaire",answer:"maïs Starlink",choices:[{val:"« Golden Rice »"},{val:"« Terminator »"},{val:"maïs Starlink"},{val:"saccage de plants transgéniques"}]},{key:"y",label:"Ce qui a été mis en exergue",answer:"risques",choices:[{val:"progrès"},{val:"avantages"},{val:"risques"},{val:"délits"}]}]},
    {type:"single",section:"synthese",q:"Introduction — Sélectionnez la problématique appropriée pour traiter le sujet.",choices:[{l:"A",t:"Pour quelles raisons les craintes liées à l'usage des OGM doivent-elles être nuancées ?"},{l:"B",t:"Dans quelle mesure faut-il interdire l'utilisation des OGM ?"},{l:"C",t:"Comment concilier précaution et progrès en matière d'usage des OGM ?"},{l:"D",t:"En quoi le recours aux OGM présente-t-il des risques pour la société ?"}],answer:"d"},
    {type:"single",section:"synthese",q:"Développement — Sélectionnez le titre approprié pour la première partie du raisonnement.",choices:[{l:"A",t:"Des risques majeurs liés à l'absence de régulation nationale et internationale en matière d'OGM."},{l:"B",t:"Les OGM, une solution contre la pauvreté et la faim dans le monde."},{l:"C",t:"Un principe de précaution justifié par l'existence de risques sanitaires et environnementaux."},{l:"D",t:"Les OGM à l'origine de progrès agricoles et médicaux significatifs."}],answer:"c"},
    {type:"fill",section:"synthese",q:"Développement — Complétez le résumé de la 1ère partie : « …porteur d'un ensemble de [w] avérés au niveau environnemental mais également au niveau [x]… insuffisances en matière d'information et [y] affectent la traçabilité… et justifient [z] des consommateurs. »",hint:"Sélectionnez la valeur correcte pour chaque variable.",vars:[{key:"w",label:"Type de conséquences avérées",answer:"risques",choices:[{val:"risques"},{val:"reculs"},{val:"progrès"},{val:"bouleversements"}]},{key:"x",label:"Niveau également concerné",answer:"sanitaire",choices:[{val:"économique"},{val:"sanitaire"},{val:"social"},{val:"politique"}]},{key:"y",label:"Insuffisances en matière de…",answer:"d'étiquetage",choices:[{val:"de prévention"},{val:"d'institutions"},{val:"de marketing"},{val:"d'étiquetage"}]},{key:"z",label:"Ce que ces insuffisances justifient",answer:"la méfiance",choices:[{val:"la méfiance"},{val:"les actes de saccage"},{val:"l'enthousiasme"},{val:"le soutien"}]}]},
    {type:"single",section:"synthese",q:"Développement — Sélectionnez le titre approprié pour la deuxième partie du raisonnement.",choices:[{l:"A",t:"Une privatisation du vivant source de domination et de dépendance."},{l:"B",t:"Un principe de précaution bafoué par des États soumis aux géants de l'agrobusiness."},{l:"C",t:"Des multinationales de biotechnologie sources d'innovation et de croissance pour les nations."},{l:"D",t:"Un cadre règlementaire extrêmement contraignant qui limite les risques liés à l'usage des OGM."}],answer:"a"},
    {type:"fill",section:"synthese",q:"Développement — Complétez le résumé de la 2ème partie : « …a colonisé le marché des semences en s'appropriant la quasi-totalité [w]… ce qui [x] la circulation des connaissances… place les agriculteurs dans une situation de [y]… ne peuvent constituer un remède efficace contre [z]. »",hint:"Sélectionnez la valeur correcte pour chaque variable.",vars:[{key:"w",label:"Ce qui a été approprié",answer:"des parts de marché",choices:[{val:"des surfaces cultivées"},{val:"des variétés de plants"},{val:"des parts de marché"},{val:"des exportations"}]},{key:"x",label:"Effet sur la circulation des connaissances",answer:"affaiblit",choices:[{val:"affaiblit"},{val:"optimise"},{val:"encourage"},{val:"anéantit"}]},{key:"y",label:"Situation des agriculteurs",answer:"grande dépendance",choices:[{val:"faillite économique"},{val:"croissance sans précédent"},{val:"grande dépendance"},{val:"supériorité"}]},{key:"z",label:"Ce contre quoi ils ne sont pas un remède",answer:"la faim dans le monde",choices:[{val:"la déforestation"},{val:"l'extrême pauvreté"},{val:"la pollution atmosphérique"},{val:"la faim dans le monde"}]}]},
    {type:"fill",section:"synthese",q:"Conclusion — Complétez le bilan : « …la répulsion des opposants semble bel et bien [x], au regard des risques que ces organismes peuvent représenter ainsi que des problèmes [y] qu'ils soulèvent. »",hint:"Sélectionnez la valeur correcte pour chaque variable.",vars:[{key:"x",label:"Qualification de la répulsion",answer:"fondée",choices:[{val:"insuffisante"},{val:"fondée"},{val:"exagérée"},{val:"injustifiée"}]},{key:"y",label:"Type de problèmes soulevés",answer:"éthiques",choices:[{val:"éthiques"},{val:"culturels"},{val:"sociaux"},{val:"géopolitiques"}]}]},
    {type:"fill",section:"synthese",q:"Conclusion — Complétez l'ouverture : « Il paraît intéressant de se demander en quoi [x] des cadres règlementaires de l'OMC et [y] peut permettre de mieux atteindre les objectifs de développement durable. »",hint:"Sélectionnez la valeur correcte pour chaque variable.",vars:[{key:"x",label:"Relation entre cadres règlementaires",answer:"la convergence",choices:[{val:"la suspension"},{val:"la convergence"},{val:"l'abrogation"},{val:"la dissociation"}]},{key:"y",label:"Second cadre concerné",answer:"du Protocole de Carthagène",choices:[{val:"de l'Union Européenne"},{val:"du Protocole de Carthagène"},{val:"du dispositif de biovigilance"},{val:"des États-Unis"}]}]},
  ]
};
